# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiderna',
            name='nuclease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grna.Nuclease'),
        ),
    ]
