# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='fasta_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='grna/genomes'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='species',
            name='genbank_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='grna/genomes'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='sequence_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='grna/targets'), upload_to=b''),
        ),
    ]
