# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grna', '0002_auto_20160310_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guiderna',
            old_name='down_seq_r',
            new_name='down_seq_c',
        ),
    ]
