# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grna', '0002_auto_20160307_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
